### ISSUE TITLE
everyport in use error

### ISSUE THREAD

**Issue by jayzhou3** [shijiezhou1/Ember-Blog#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

https://stackoverflow.com/questions/57535688/ember-serve-every-port-is-in-use

**Comment by shijiezhou1** [comment]
fixed after install "portfinder": "^1.0.21"

npm install portfinder@1.0.21
